In [3]:
import tensorflow as tf

2023-06-15 17:07:21.938748: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-06-15 17:07:22.234721: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-06-15 17:07:22.236084: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-06-15 17:07:23.604045: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


In [4]:
daily_sales_numbers = [21, 22, -108, 31, -1, 32, 34,31]

tf_dataset = tf.data.Dataset.from_tensor_slices(daily_sales_numbers)
tf_dataset

2023-06-15 17:07:26.346235: E tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected


<_TensorSliceDataset element_spec=TensorSpec(shape=(), dtype=tf.int32, name=None)>

In [5]:
for sales in tf_dataset:
    print(sales.numpy())

21
22
-108
31
-1
32
34
31


2023-06-15 17:07:26.780825: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype int32 and shape [8]
	 [[{{node Placeholder/_0}}]]


In [6]:
for sales in tf_dataset.as_numpy_iterator():
    print(sales)

21
22
-108
31
-1
32
34
31


In [7]:
images_ds = tf.data.Dataset.list_files('/home/codetrade/Downloads/CSV/PetImages/*/*', shuffle=False)

In [8]:
image_count = len(images_ds)
image_count

24961

In [9]:
type(images_ds)

tensorflow.python.data.ops.from_tensor_slices_op._TensorSliceDataset

In [10]:
for file in images_ds.take(3):
    print(file.numpy())

b'/home/codetrade/Downloads/CSV/PetImages/Cat/0.jpg'
b'/home/codetrade/Downloads/CSV/PetImages/Cat/1.jpg'
b'/home/codetrade/Downloads/CSV/PetImages/Cat/10.jpg'


2023-06-15 17:07:29.007750: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype string and shape [24961]
	 [[{{node Placeholder/_0}}]]


In [11]:
mages_ds = images_ds.shuffle(200)
for file in images_ds.take(3):
    print(file.numpy())

b'/home/codetrade/Downloads/CSV/PetImages/Cat/0.jpg'
b'/home/codetrade/Downloads/CSV/PetImages/Cat/1.jpg'
b'/home/codetrade/Downloads/CSV/PetImages/Cat/10.jpg'


2023-06-15 17:07:29.360751: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype string and shape [24961]
	 [[{{node Placeholder/_0}}]]


In [12]:
class_names = ["Cat","Dog"]

In [13]:
train_size = int(image_count*0.8)
train_ds = images_ds.take(train_size)
test_ds = images_ds.skip(train_size)

In [14]:
len(train_ds)

19968

In [15]:
len(test_ds)

4993

In [16]:
s = 'home/codetrade/Downloads/CSV/PetImages/Cat/10.jpg'
s.split('/')[4:5]

['PetImages']

In [17]:
def get_label(file_path):
    import os
    return tf.strings.split(file_path,os.path.sep)[-2]

In [18]:
def process_image(file_path):
    label=get_label(file_path)
    img=tf.io.read_file(file_path)
    img=tf.image.decode_jpeg(img)
    img=tf.image.resize(img,[128,128])
    
    return img,label

In [19]:
for t in train_ds.take(4):
    print(t.numpy())

b'/home/codetrade/Downloads/CSV/PetImages/Cat/0.jpg'
b'/home/codetrade/Downloads/CSV/PetImages/Cat/1.jpg'
b'/home/codetrade/Downloads/CSV/PetImages/Cat/10.jpg'
b'/home/codetrade/Downloads/CSV/PetImages/Cat/100.jpg'


2023-06-15 17:07:34.248478: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype string and shape [24961]
	 [[{{node Placeholder/_0}}]]


In [20]:
for label in train_ds.map(get_label):
    print(label)

2023-06-15 17:07:35.108444: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype string and shape [24961]
	 [[{{node Placeholder/_0}}]]


tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=

tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=

tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=

tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=

tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=

tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=

tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=

tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=

tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=

tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=

tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=

tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=

tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=

In [21]:
train_ds= train_ds.map(process_image)
for img, label in train_ds.take(3):
    print(img)
    print(label)

tf.Tensor(
[[[202.45312   165.45312    87.453125 ]
  [206.35938   169.35938    91.359375 ]
  [209.26562   172.26562    94.265625 ]
  ...
  [244.73438   207.        124.53125  ]
  [242.        204.        119.71875  ]
  [238.45312   201.45312   120.453125 ]]

 [[202.45312   165.45312    87.453125 ]
  [206.35938   169.35938    91.359375 ]
  [209.26562   172.26562    94.265625 ]
  ...
  [244.76239   208.31506   126.84509  ]
  [243.        205.64294   122.32147  ]
  [239.40533   202.40533   121.405334 ]]

 [[202.45312   165.45312    87.453125 ]
  [206.35938   169.35938    91.359375 ]
  [209.26562   172.26562    94.265625 ]
  ...
  [245.        210.        128.87091  ]
  [243.        206.        125.       ]
  [240.45312   203.45312   122.453125 ]]

 ...

 [[157.47266   125.         54.17578  ]
  [158.47266   126.         55.17578  ]
  [159.64844   127.17578    56.351562 ]
  ...
  [  3.          4.          0.       ]
  [  3.          4.          0.       ]
  [  2.1757812   3.1757812   0.  

2023-06-15 17:07:37.789206: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype string and shape [24961]
	 [[{{node Placeholder/_0}}]]


In [22]:
def scale(image,label):
    return image/255, label

In [24]:
train_ds=train_ds.map(scale)
for image,label in train_ds.take(2):
    print("******Image: ",image.numpy()[0][0])
    print("******Lable: ",image.numpy())
    

******Image:  [0.00311347 0.00254445 0.00134492]
******Lable:  [[[3.1134658e-03 2.5444541e-03 1.3449155e-03]
  [3.1735389e-03 2.6045272e-03 1.4049885e-03]
  [3.2182334e-03 2.6492216e-03 1.4496827e-03]
  ...
  [3.7636966e-03 3.1833909e-03 1.9151288e-03]
  [3.7216456e-03 3.1372549e-03 1.8411188e-03]
  [3.6670992e-03 3.0980872e-03 1.8524126e-03]]

 [[3.1134658e-03 2.5444541e-03 1.3449155e-03]
  [3.1735389e-03 2.6045272e-03 1.4049885e-03]
  [3.2182334e-03 2.6492216e-03 1.4496827e-03]
  ...
  [3.7641276e-03 3.2036151e-03 1.9507126e-03]
  [3.7370243e-03 3.1625212e-03 1.8811453e-03]
  [3.6817428e-03 3.1127310e-03 1.8670562e-03]]

 [[3.1134658e-03 2.5444541e-03 1.3449155e-03]
  [3.1735389e-03 2.6045272e-03 1.4049885e-03]
  [3.2182334e-03 2.6492216e-03 1.4496827e-03]
  ...
  [3.7677817e-03 3.2295270e-03 1.9818670e-03]
  [3.7370243e-03 3.1680122e-03 1.9223376e-03]
  [3.6978566e-03 3.1288445e-03 1.8831700e-03]]

 ...

 [[2.4217248e-03 1.9223376e-03 8.3315314e-04]
  [2.4371035e-03 1.9377163e-03 8.

2023-06-15 17:10:45.736603: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype string and shape [24961]
	 [[{{node Placeholder/_0}}]]
