In [2]:
# 1. Using supervised learning :- usig this techniques to solve the NLP problems
#                              like: food review systems, weather food is negative or possitive

# 2. Using self-supervised learning
#     1. Word2vec
#     2. Glove


In [13]:
import numpy as np
import pandas as pd
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

In [5]:
reviews = [
    'nice food',
    'amazing restaurant',
    'too good',
    'just leave it!',
    'will go agian',
    'horrible food',
    'never go there',
    'poor service',
    'poor quality',
    'need improvement'
]
sentiment= np.array([1,1,1,1,1,0,0,0,0,0])

In [6]:
one_hot("amazing restaurant",30)

[23, 3]

In [10]:
vocab_size=30
encoding_reviews = [one_hot(d,vocab_size)for d in reviews]
encoding_reviews

[[6, 24],
 [23, 3],
 [20, 17],
 [2, 27, 23],
 [11, 4, 23],
 [22, 24],
 [10, 4, 20],
 [10, 25],
 [10, 9],
 [17, 4]]

In [15]:
# Padding in this diamension
max_length = 3
padded_reviews = pad_sequences(encoding_reviews, maxlen=max_length, padding='post')
padded_reviews

array([[ 6, 24,  0],
       [23,  3,  0],
       [20, 17,  0],
       [ 2, 27, 23],
       [11,  4, 23],
       [22, 24,  0],
       [10,  4, 20],
       [10, 25,  0],
       [10,  9,  0],
       [17,  4,  0]], dtype=int32)

In [16]:
embeded_vector_size = 5

model = Sequential()
model.add(Embedding(vocab_size, embeded_vector_size, input_length=max_length,name="embedding"))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

2023-06-12 14:16:41.423413: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2023-06-12 14:16:41.424740: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-06-12 14:16:41.427500: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.


In [17]:
X = padded_reviews
y = sentiment

In [18]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 3, 5)              150       
_________________________________________________________________
flatten (Flatten)            (None, 15)                0         
_________________________________________________________________
dense (Dense)                (None, 1)                 16        
Total params: 166
Trainable params: 166
Non-trainable params: 0
_________________________________________________________________
None


In [19]:
model.fit(X, y, epochs=50, verbose=0)

2023-06-12 14:19:33.377829: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:116] None of the MLIR optimization passes are enabled (registered 2)
2023-06-12 14:19:33.406859: I tensorflow/core/platform/profile_utils/cpu_utils.cc:112] CPU Frequency: 3693085000 Hz


In [20]:
loss, accuracy = model.evaluate(X, y)
accuracy

1/1 [==============================] - 0s 165ms/step - loss: 0.6128 - accuracy: 1.0000


1.0

In [21]:
weights = model.get_layer('embedding').get_weights()[0]
len(weights)

30

In [22]:
weights[13]

array([ 0.00808223, -0.04119736, -0.01985074,  0.03012102,  0.04512305],
      dtype=float32)

In [23]:
weights[6]

array([-0.04349419, -0.0649444 ,  0.08463103,  0.07608984, -0.03010977],
      dtype=float32)

In [24]:
weights[18]

array([ 0.03022612, -0.0417146 ,  0.026705  ,  0.02793964, -0.02818413],
      dtype=float32)