In [1]:
import tensorflow as tf


2023-06-14 14:35:50.998020: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-06-14 14:35:51.045864: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-06-14 14:35:51.046451: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-06-14 14:35:51.970557: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


In [2]:
daily_sales_number=[12,22,-108,31,-1,32,34,31]

In [3]:
tf_dataset=tf.data.Dataset.from_tensor_slices(daily_sales_number)
tf_dataset

2023-06-14 14:35:53.119439: E tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected


<_TensorSliceDataset element_spec=TensorSpec(shape=(), dtype=tf.int32, name=None)>

In [4]:
for sales in tf_dataset:
    print(sales.numpy())

12
22
-108
31
-1
32
34
31


2023-06-14 14:35:53.164646: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype int32 and shape [8]
	 [[{{node Placeholder/_0}}]]


In [5]:
# importing library
import tensorflow as tf  
# creating a list object- monthly expenses in dollars 
dataset = [12,15,67,-56,78,90,25,-890,-45,67,90,45,34,-100,300]
  
# creating tf.data.dataset object  
tf_dataset = tf.data.Dataset.from_tensor_slices(dataset) 
tf_dataset

<_TensorSliceDataset element_spec=TensorSpec(shape=(), dtype=tf.int32, name=None)>

In [6]:
for i in tf_dataset:
    print(i)

tf.Tensor(12, shape=(), dtype=int32)
tf.Tensor(15, shape=(), dtype=int32)
tf.Tensor(67, shape=(), dtype=int32)
tf.Tensor(-56, shape=(), dtype=int32)
tf.Tensor(78, shape=(), dtype=int32)
tf.Tensor(90, shape=(), dtype=int32)
tf.Tensor(25, shape=(), dtype=int32)
tf.Tensor(-890, shape=(), dtype=int32)
tf.Tensor(-45, shape=(), dtype=int32)
tf.Tensor(67, shape=(), dtype=int32)
tf.Tensor(90, shape=(), dtype=int32)
tf.Tensor(45, shape=(), dtype=int32)
tf.Tensor(34, shape=(), dtype=int32)
tf.Tensor(-100, shape=(), dtype=int32)
tf.Tensor(300, shape=(), dtype=int32)


2023-06-14 14:35:53.203873: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype int32 and shape [15]
	 [[{{node Placeholder/_0}}]]


In [7]:
for i in tf_dataset:
    print(i.numpy())

12
15
67
-56
78
90
25
-890
-45
67
90
45
34
-100
300


In [8]:
## previous code and these code are the same working model
for i in tf_dataset.as_numpy_iterator():     
    print(i)

12
15
67
-56
78
90
25
-890
-45
67
90
45
34
-100
300


In [9]:
tf_dataset = tf_dataset.filter(lambda x : x>0)
for i in tf_dataset.as_numpy_iterator():
    print('$ '+str(i))

$ 12
$ 15
$ 67
$ 78
$ 90
$ 25
$ 67
$ 90
$ 45
$ 34
$ 300


2023-06-14 14:35:53.279038: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype int32 and shape [15]
	 [[{{node Placeholder/_0}}]]


In [10]:
for i in tf_dataset.map(lambda x : x*82):
    print('Rs '+str(i.numpy()))

2023-06-14 14:35:53.349135: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype int32 and shape [15]
	 [[{{node Placeholder/_0}}]]


Rs 984
Rs 1230
Rs 5494
Rs 6396
Rs 7380
Rs 2050
Rs 5494
Rs 7380
Rs 3690
Rs 2788
Rs 24600


In [11]:
for i in tf_dataset.shuffle(3):
    print(i.numpy())

12
67
90
15
78
25
90
45
34
67
300


2023-06-14 14:42:26.401250: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype int32 and shape [15]
	 [[{{node Placeholder/_0}}]]
2023-06-14 14:42:26.401564: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype int32 and shape [15]
	 [[{{node Placeholder/_0}}]]


In [12]:
for i in tf_dataset.batch(3):
    print(i.numpy())

[12 15 67]
[78 90 25]
[67 90 45]
[ 34 300]


2023-06-14 14:44:41.451354: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype int32 and shape [15]
	 [[{{node Placeholder/_0}}]]


In [13]:
tf_dataset_new = tf.data.Dataset.from_tensor_slices(dataset).filter(lambda x: x>0).map(lambda a: a*82).shuffle(2).batch(2)
for i in tf_dataset_new.as_numpy_iterator():
    print(i)

[1230 5494]
[6396  984]
[7380 5494]
[7380 2050]
[3690 2788]
[24600]


2023-06-14 14:46:38.983572: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype int32 and shape [15]
	 [[{{node Placeholder/_0}}]]
2023-06-14 14:46:38.983869: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype int32 and shape [15]
	 [[{{node Placeholder/_0}}]]
