In [1]:
from tensorflow.keras.preprocessing.text import one_hot


2023-05-19 12:58:02.613595: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-05-19 12:58:02.656652: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-05-19 12:58:02.657655: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-05-19 12:58:03.411783: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


In [2]:
sent = [
    'the glass of the milk',
    'the glass of juice',
    'the cup of tea',
    'i am a good boy',
    'i am a good developer',
    'understand the meaning of the word',
    'your voice are good'
]

In [3]:
sent

['the glass of the milk',
 'the glass of juice',
 'the cup of tea',
 'i am a good boy',
 'i am a good developer',
 'understand the meaning of the word',
 'your voice are good']

In [5]:
# Vocabulary size
voc_size = 10000

In [6]:
# One hot representation
one_repr = [one_hot(word,voc_size) for word in sent]
print(one_repr)

[[2040, 8236, 4933, 2040, 9630], [2040, 8236, 4933, 1592], [2040, 6152, 4933, 5712], [7041, 6550, 7238, 7407, 5299], [7041, 6550, 7238, 7407, 6282], [5209, 2040, 2720, 4933, 2040, 4373], [4116, 6434, 4723, 7407]]


In [7]:
# Word embedding representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length = 8
embedded_docs = pad_sequences(one_repr,padding='pre', maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 2040 8236 4933 2040 9630]
 [   0    0    0    0 2040 8236 4933 1592]
 [   0    0    0    0 2040 6152 4933 5712]
 [   0    0    0 7041 6550 7238 7407 5299]
 [   0    0    0 7041 6550 7238 7407 6282]
 [   0    0 5209 2040 2720 4933 2040 4373]
 [   0    0    0    0 4116 6434 4723 7407]]


In [11]:
dim=10

In [12]:
model = Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [13]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [14]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 119ms/step
[[[-0.0299552   0.02725656  0.01827342 -0.01805962  0.01543187
   -0.03538378  0.01134346  0.01451683 -0.02422564  0.04840132]
  [-0.0299552   0.02725656  0.01827342 -0.01805962  0.01543187
   -0.03538378  0.01134346  0.01451683 -0.02422564  0.04840132]
  [-0.0299552   0.02725656  0.01827342 -0.01805962  0.01543187
   -0.03538378  0.01134346  0.01451683 -0.02422564  0.04840132]
  [-0.02513602 -0.00059172 -0.04114803  0.03168824  0.00699341
   -0.03351659  0.01657483  0.04088273  0.01563315 -0.0345419 ]
  [-0.02241967 -0.0397812  -0.031795    0.03555042  0.00145037
   -0.03892352  0.00929326  0.04354778  0.04273111 -0.01560917]
  [-0.00670888  0.02121378 -0.01190763 -0.04256833  0.02013595
    0.02378045  0.01627943 -0.00650205 -0.02566131 -0.030116  ]
  [-0.02513602 -0.00059172 -0.04114803  0.03168824  0.00699341
   -0.03351659  0.01657483  0.04088273  0.01563315 -0.0345419 ]
  [-0.01540023 -0.04378518 -0.04970453  0.02517379 -0.0086

In [15]:
embedded_docs[0]

array([   0,    0,    0, 2040, 8236, 4933, 2040, 9630], dtype=int32)

In [16]:
print(model.predict(embedded_docs)[0])

1/1 [==============================] - 0s 17ms/step
[[-0.0299552   0.02725656  0.01827342 -0.01805962  0.01543187 -0.03538378
   0.01134346  0.01451683 -0.02422564  0.04840132]
 [-0.0299552   0.02725656  0.01827342 -0.01805962  0.01543187 -0.03538378
   0.01134346  0.01451683 -0.02422564  0.04840132]
 [-0.0299552   0.02725656  0.01827342 -0.01805962  0.01543187 -0.03538378
   0.01134346  0.01451683 -0.02422564  0.04840132]
 [-0.02513602 -0.00059172 -0.04114803  0.03168824  0.00699341 -0.03351659
   0.01657483  0.04088273  0.01563315 -0.0345419 ]
 [-0.02241967 -0.0397812  -0.031795    0.03555042  0.00145037 -0.03892352
   0.00929326  0.04354778  0.04273111 -0.01560917]
 [-0.00670888  0.02121378 -0.01190763 -0.04256833  0.02013595  0.02378045
   0.01627943 -0.00650205 -0.02566131 -0.030116  ]
 [-0.02513602 -0.00059172 -0.04114803  0.03168824  0.00699341 -0.03351659
   0.01657483  0.04088273  0.01563315 -0.0345419 ]
 [-0.01540023 -0.04378518 -0.04970453  0.02517379 -0.00864542  0.00545518